import { create } from 'zustand';

const useUserAuth = create<UserAuth>((set) => ({
  uid: '',
  phone: '',
  isloggedIn: false,
  email: '',
  cnic: '',
  phoneNo: '',
  name: '',
  aldolat: '',
  almadina: '',
  almontaqatha: '',
  approval: '',
  date: '',
  status: '',
  role: [],
  setisloggedIn({ email, name, phoneNo, role, uid, isloggedIn }) {
    set((state) => ({
      ...state,
      email,
      name,
      phoneNo,
      role,
      isloggedIn,
      uid,
    }));
  },
  setuser({
    email,
    name,
    phoneNo,
    role,
    uid,
    aldolat,
    almadina,
    almontaqatha,
    approval,
    cnic,
    date,
    status,
    capacity,
    wakeelCNIC,
    wakeelDate,
    wakeelDescription,
    wakeelName,
    wakeelPNO,
    wakeelAttachedFile1,
    wakeelAttachedFile2,
  }) {
    set((state) => ({
      ...state,
      email,
      name,
      phoneNo,
      uid,
      aldolat,
      almadina,
      almontaqatha,
      approval,
      cnic,
      date,
      status,
      capacity,
      wakeelCNIC,
      wakeelDate,
      wakeelDescription,
      wakeelName,
      wakeelPNO,
      wakeelAttachedFile1,
      wakeelAttachedFile2,
    }));
  },
}));

export default useUserAuth;
